name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: windows-latest
          - os: macos-latest
          - os: ubuntu-latest

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install Linux dependencies
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev

      - name: Install frontend dependencies
        run: npm install

      - name: Run frontend type check
        run: npm run check

      - name: Build frontend
        run: npm run build

      - name: Create dummy OAuth2 credentials
        run: cp src-tauri/oauth2_credentials.json.example src-tauri/oauth2_credentials.json

      - name: Format Rust code
        working-directory: src-tauri
        run: cargo fmt --check

      - name: Rust check
        working-directory: src-tauri
        run: cargo check

      - name: Rust clippy
        working-directory: src-tauri
        run: cargo clippy -- -D warnings
