name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
          - os: macos-latest
            rust_target: aarch64-apple-darwin

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.rust_target }}

      - name: Install frontend dependencies
        run: npm install

      - name: Create OAuth2 credentials from secret
        if: secrets.OAUTH_CREDENTIALS_JSON != ''
        run: echo "${{ secrets.OAUTH_CREDENTIALS_JSON }}" > src-tauri/oauth2_credentials.json

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Colimail ${{ github.ref_name }}'
          releaseBody: |
            See the assets below to download this version and install.

            ## Installation
            - **Windows**: Download `.msi` installer
            - **macOS Apple Silicon**: Download `.dmg` file

            ## What's New
            Check the [changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.platform.os == 'macos-latest' && format('--target {0}', matrix.platform.rust_target) || '' }}

      - name: Upload artifacts (Windows)
        if: matrix.platform.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: colimail-${{ matrix.platform.os }}-${{ matrix.platform.rust_target }}
          path: src-tauri/target/release/bundle/**/*.msi

      - name: Upload artifacts (macOS)
        if: matrix.platform.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: colimail-${{ matrix.platform.os }}-${{ matrix.platform.rust_target }}
          path: src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
